language: c

install:
  - git clone git://github.com/raspberrypi/tools.git
  - export PATH=$PATH:$HOME/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin
  - export CC=arm-linux-gnueabihf-gcc

script: make
